import { ArchitectureProject } from "@/types";

export const architectureProjects: ArchitectureProject[] = [
  {
    id: "sentinel-datacore",
    title: "SentinelDataCore",
    subtitle: "Express API request traversal map",
    overview:
      "Client requests enter the Express API, then branch through authentication, cache, rate limiting and persistence paths for secure and fast handling.",
    canvas: { width: 1200, height: 720 },
    nodes: [
      {
        id: "sentinel-client",
        label: "Client",
        category: "frontend",
        x: 600,
        y: 80,
        role: "Sends API requests and receives responses from the backend.",
        tech: ["Web Client"],
      },
      {
        id: "sentinel-api",
        label: "Express.js API",
        category: "api",
        x: 600,
        y: 220,
        role: "Main request router that orchestrates auth, cache, rate limits and persistence.",
        tech: ["Node.js", "Express"],
      },
      {
        id: "sentinel-auth",
        label: "JWT Authentication",
        category: "service",
        x: 220,
        y: 220,
        role: "Validates and decodes JWTs before protected operations are allowed.",
        tech: ["JWT", "Middleware"],
      },
      {
        id: "sentinel-admin",
        label: "Admin Operations",
        category: "service",
        x: 220,
        y: 420,
        role: "Executes privileged admin actions only after successful authentication.",
        tech: ["RBAC", "Protected Routes"],
      },
      {
        id: "sentinel-cache",
        label: "LRU Cache",
        category: "cache",
        x: 460,
        y: 220,
        role: "Stores hot responses to serve repeated requests with low latency.",
        tech: ["LRU", "In-memory Cache"],
      },
      {
        id: "sentinel-fast",
        label: "Fast Data Retrieval",
        category: "service",
        x: 460,
        y: 420,
        role: "Returns cached responses quickly when cache hits occur.",
        tech: ["Hot Path Serving"],
      },
      {
        id: "sentinel-rate",
        label: "Rate Limiter",
        category: "service",
        x: 740,
        y: 220,
        role: "Applies throttling rules to prevent API abuse and traffic spikes.",
        tech: ["Request Throttling"],
      },
      {
        id: "sentinel-abuse",
        label: "Abuse Prevention",
        category: "service",
        x: 740,
        y: 420,
        role: "Blocks or slows abusive patterns after rate-limit enforcement.",
        tech: ["Security Rules"],
      },
      {
        id: "sentinel-db",
        label: "MongoDB Atlas",
        category: "database",
        x: 980,
        y: 220,
        role: "Primary data store for application records and query results.",
        tech: ["MongoDB Atlas"],
      },
      {
        id: "sentinel-persist",
        label: "Data Persistence",
        category: "service",
        x: 980,
        y: 420,
        role: "Handles durable writes and retrieval consistency over persisted data.",
        tech: ["Write/Read Workflows"],
      },
    ],
    edges: [
      { id: "s1", from: "sentinel-client", to: "sentinel-api", flow: "API Request", labelDy: -8 },
      { id: "s2", from: "sentinel-api", to: "sentinel-auth", flow: "Auth Check", labelDy: -8 },
      { id: "s3", from: "sentinel-auth", to: "sentinel-admin", flow: "Authorized Access", labelDx: -8 },
      { id: "s4", from: "sentinel-api", to: "sentinel-cache", flow: "Cache Check", labelDy: -8 },
      { id: "s5", from: "sentinel-cache", to: "sentinel-fast", flow: "Cache Hit Path", labelDx: -6 },
      { id: "s6", from: "sentinel-api", to: "sentinel-rate", flow: "Throttle Rules", labelDy: -8 },
      { id: "s7", from: "sentinel-rate", to: "sentinel-abuse", flow: "Abuse Control", labelDx: 6 },
      { id: "s8", from: "sentinel-api", to: "sentinel-db", flow: "DB Query", labelDy: -8 },
      { id: "s9", from: "sentinel-db", to: "sentinel-persist", flow: "Persistence Layer", labelDx: 8 },
    ],
  },
  {
    id: "ums-chatbot",
    title: "UMS Chatbot",
    subtitle: "SDE-3 scalable production architecture",
    overview:
      "Production-grade design with gateway controls, session/cache tier, async ingestion workers, vector refresh, and observability across API and model pipeline.",
    canvas: { width: 1400, height: 780 },
    nodes: [
      {
        id: "sde3-client",
        label: "Web/Mobile Client",
        category: "frontend",
        x: 120,
        y: 300,
        role: "Sends chatbot queries and receives streamed responses.",
        tech: ["React", "SSE/WebSocket"],
      },
      {
        id: "sde3-gateway",
        label: "API Gateway",
        category: "api",
        x: 340,
        y: 300,
        role: "Entry point for auth, throttling and routing into RAG orchestration.",
        tech: ["Express", "Routing", "Validation"],
      },
      {
        id: "sde3-auth",
        label: "Auth + Rate Control",
        category: "service",
        x: 340,
        y: 150,
        role: "Handles JWT verification, role checks and per-user request limits.",
        tech: ["JWT", "RBAC", "Rate Limiting"],
      },
      {
        id: "sde3-session",
        label: "Session/Cache Store",
        category: "cache",
        x: 560,
        y: 150,
        role: "Caches chat context and recent retrieval results for low-latency turns.",
        tech: ["Redis", "TTL Cache"],
      },
      {
        id: "sde3-orch",
        label: "RAG Orchestrator",
        category: "service",
        x: 560,
        y: 300,
        role: "Coordinates retrieval, prompt construction, model call and response shaping.",
        tech: ["Python", "LangChain"],
      },
      {
        id: "sde3-retrieval",
        label: "Retrieval Service",
        category: "service",
        x: 800,
        y: 220,
        role: "Executes semantic search and metadata joins for top-k grounding context.",
        tech: ["Retriever", "Re-ranking"],
      },
      {
        id: "sde3-guard",
        label: "Prompt + Guardrails",
        category: "service",
        x: 800,
        y: 380,
        role: "Builds policy-compliant prompts and filters unsafe model output.",
        tech: ["Prompt Templates", "Safety Rules"],
      },
      {
        id: "sde3-vector",
        label: "Vector Index",
        category: "database",
        x: 1040,
        y: 190,
        role: "Stores embeddings and serves nearest-neighbor search.",
        tech: ["FAISS", "Embeddings"],
      },
      {
        id: "sde3-knowledge",
        label: "Knowledge Store",
        category: "database",
        x: 1040,
        y: 310,
        role: "Holds structured academic policies, schedules and metadata.",
        tech: ["PostgreSQL", "JSON Docs"],
      },
      {
        id: "sde3-llm",
        label: "LLM Provider",
        category: "external",
        x: 1040,
        y: 430,
        role: "Generates grounded responses from prompt and retrieved context.",
        tech: ["OpenAI API"],
      },
      {
        id: "sde3-queue",
        label: "Async Queue",
        category: "service",
        x: 560,
        y: 500,
        role: "Buffers non-blocking tasks such as ingestion and re-indexing jobs.",
        tech: ["BullMQ / RabbitMQ"],
      },
      {
        id: "sde3-ingest",
        label: "Ingestion Workers",
        category: "service",
        x: 800,
        y: 540,
        role: "Parses documents, chunks content and triggers embedding refresh.",
        tech: ["Workers", "Chunking ETL"],
      },
      {
        id: "sde3-docs",
        label: "Document Store",
        category: "database",
        x: 1040,
        y: 580,
        role: "Stores raw PDFs and processed documents for replayable indexing.",
        tech: ["Object Storage"],
      },
      {
        id: "sde3-observability",
        label: "Observability",
        category: "service",
        x: 1280,
        y: 320,
        role: "Aggregates metrics, traces and logs for API, retrieval and worker tiers.",
        tech: ["OpenTelemetry", "Dashboards"],
      },
    ],
    edges: [
      { id: "su1", from: "sde3-client", to: "sde3-gateway", flow: "HTTPS Query", labelDy: -10 },
      { id: "su2", from: "sde3-gateway", to: "sde3-auth", flow: "JWT + ACL", labelDx: -28, labelDy: -6 },
      { id: "su3", from: "sde3-auth", to: "sde3-gateway", flow: "Permit/Deny", labelDx: -38, labelDy: 10 },
      { id: "su4", from: "sde3-gateway", to: "sde3-session", flow: "Session Lookup", labelDy: -10, curve: -22 },
      { id: "su5", from: "sde3-session", to: "sde3-gateway", flow: "Context State", labelDy: 12, curve: 22 },
      { id: "su6", from: "sde3-gateway", to: "sde3-orch", flow: "RAG Route", labelDy: -10 },
      { id: "su7", from: "sde3-orch", to: "sde3-retrieval", flow: "Top-K Retrieve", labelDy: -8 },
      { id: "su8", from: "sde3-retrieval", to: "sde3-vector", flow: "Vector Search", labelDx: 30, labelDy: -6 },
      { id: "su9", from: "sde3-retrieval", to: "sde3-knowledge", flow: "Metadata Fetch", labelDx: 36, labelDy: -6 },
      { id: "su10", from: "sde3-orch", to: "sde3-guard", flow: "Prompt Build", labelDy: -8 },
      { id: "su11", from: "sde3-guard", to: "sde3-llm", flow: "LLM Completion", labelDx: 38, labelDy: -6 },
      { id: "su12", from: "sde3-llm", to: "sde3-orch", flow: "Model Output", labelDx: -42, labelDy: 10 },
      { id: "su13", from: "sde3-orch", to: "sde3-gateway", flow: "Final Answer", labelDy: 12 },
      { id: "su14", from: "sde3-gateway", to: "sde3-client", flow: "SSE Stream", labelDy: 12 },
      { id: "su15", from: "sde3-orch", to: "sde3-queue", flow: "Async Tasks", labelDx: -16, labelDy: 8 },
      { id: "su16", from: "sde3-queue", to: "sde3-ingest", flow: "Ingest Job", labelDy: 6 },
      { id: "su17", from: "sde3-ingest", to: "sde3-docs", flow: "Doc Store", labelDx: 30 },
      { id: "su18", from: "sde3-ingest", to: "sde3-vector", flow: "Re-index", labelDx: 32, curve: -20 },
      { id: "su19", from: "sde3-gateway", to: "sde3-observability", flow: "API Metrics", labelDx: 62, labelDy: -8 },
      { id: "su20", from: "sde3-orch", to: "sde3-observability", flow: "Trace Spans", labelDx: 62, labelDy: 0 },
      { id: "su21", from: "sde3-ingest", to: "sde3-observability", flow: "Pipeline Logs", labelDx: 58, labelDy: 10 },
    ],
  },
  {
    id: "proxy-server",
    title: "Multi-Threaded Proxy Server",
    subtitle: "Thread manager + worker pool + shared cache architecture",
    overview:
      "Client requests are accepted by the main socket, distributed by a thread manager to worker threads, resolved via shared LRU cache and dispatched to target servers on cache misses.",
    canvas: { width: 1300, height: 760 },
    nodes: [
      {
        id: "proxy-main-socket",
        label: "Main Server Socket",
        category: "api",
        x: 760,
        y: 120,
        role: "Accepts client TCP connections and routes sockets into the thread manager.",
        tech: ["Socket Server", "Connection Accept Loop"],
      },
      {
        id: "proxy-thread-manager",
        label: "Thread Manager",
        category: "service",
        x: 640,
        y: 220,
        role: "Assigns accepted sockets to worker threads and manages thread lifecycle.",
        tech: ["Dispatcher", "Scheduler"],
      },
      {
        id: "proxy-worker-1",
        label: "Worker Thread 1",
        category: "service",
        x: 500,
        y: 340,
        role: "Handles request parsing, cache access and origin forwarding for assigned sockets.",
        tech: ["C++ Thread", "Request Handler"],
      },
      {
        id: "proxy-worker-2",
        label: "Worker Thread 2",
        category: "service",
        x: 680,
        y: 340,
        role: "Processes requests concurrently with synchronized access to shared resources.",
        tech: ["C++ Thread", "Concurrency Control"],
      },
      {
        id: "proxy-worker-n",
        label: "Worker Thread N",
        category: "service",
        x: 860,
        y: 340,
        role: "Scales throughput by serving additional concurrent client connections.",
        tech: ["Thread Pool"],
      },
      {
        id: "proxy-lru",
        label: "LRU Cache",
        category: "cache",
        x: 680,
        y: 500,
        role: "Stores hot responses for O(1) lookup and eviction across worker threads.",
        tech: ["LRU", "Shared Cache"],
      },
      {
        id: "proxy-logging",
        label: "Logging System",
        category: "database",
        x: 900,
        y: 500,
        role: "Collects per-request and per-thread telemetry for diagnostics and tuning.",
        tech: ["Structured Logs", "Metrics"],
      },
      {
        id: "proxy-hashmap",
        label: "HashMap",
        category: "cache",
        x: 560,
        y: 640,
        role: "Maps cache keys to linked-list nodes for constant-time cache access.",
        tech: ["unordered_map"],
      },
      {
        id: "proxy-dll",
        label: "Doubly Linked List",
        category: "cache",
        x: 700,
        y: 640,
        role: "Tracks LRU ordering for O(1) promotions and evictions.",
        tech: ["Doubly Linked List"],
      },
      {
        id: "proxy-mutex",
        label: "Mutex Lock",
        category: "service",
        x: 840,
        y: 640,
        role: "Protects cache structures from race conditions across worker threads.",
        tech: ["Mutex", "Critical Sections"],
      },
      {
        id: "proxy-target-1",
        label: "Target Server 1",
        category: "external",
        x: 100,
        y: 500,
        role: "Origin endpoint used when cache misses occur for routed requests.",
        tech: ["HTTP Origin"],
      },
      {
        id: "proxy-target-2",
        label: "Target Server 2",
        category: "external",
        x: 250,
        y: 500,
        role: "Additional upstream server for routed requests.",
        tech: ["HTTP Origin"],
      },
      {
        id: "proxy-target-n",
        label: "Target Server N...",
        category: "external",
        x: 400,
        y: 500,
        role: "Represents additional upstream targets for scalable forwarding.",
        tech: ["HTTP Origin Pool"],
      },
      {
        id: "proxy-client-1",
        label: "Client 1",
        category: "frontend",
        x: 1120,
        y: 120,
        role: "Sends requests to the proxy and receives proxied responses.",
        tech: ["HTTP Client"],
      },
      {
        id: "proxy-client-2",
        label: "Client 2",
        category: "frontend",
        x: 1040,
        y: 500,
        role: "Concurrent client connection handled by thread pool workers.",
        tech: ["HTTP Client"],
      },
      {
        id: "proxy-client-n",
        label: "Client N...",
        category: "frontend",
        x: 1180,
        y: 500,
        role: "Additional clients served concurrently by available worker threads.",
        tech: ["HTTP Client Pool"],
      },
    ],
    edges: [
      { id: "p1", from: "proxy-client-1", to: "proxy-main-socket", flow: "Inbound Request" },
      { id: "p2", from: "proxy-client-2", to: "proxy-main-socket", flow: "Inbound Request", curve: 24, labelDx: 38, labelDy: -8 },
      { id: "p3", from: "proxy-client-n", to: "proxy-main-socket", flow: "Inbound Request", curve: 46, labelDx: 42, labelDy: -12 },
      { id: "p4", from: "proxy-main-socket", to: "proxy-thread-manager", flow: "Connection Dispatch", labelDx: -26, labelDy: -10 },
      { id: "p5", from: "proxy-thread-manager", to: "proxy-worker-1", flow: "Assign Socket", labelDx: -26, labelDy: -8 },
      { id: "p6", from: "proxy-thread-manager", to: "proxy-worker-2", flow: "Assign Socket", labelDy: -8 },
      { id: "p7", from: "proxy-thread-manager", to: "proxy-worker-n", flow: "Assign Socket", labelDx: 26, labelDy: -8 },
      { id: "p8", from: "proxy-worker-1", to: "proxy-target-1", flow: "Origin Fetch", curve: -30, labelDx: -26 },
      { id: "p9", from: "proxy-worker-2", to: "proxy-target-2", flow: "Origin Fetch", curve: -22, labelDx: -14 },
      { id: "p10", from: "proxy-worker-n", to: "proxy-target-n", flow: "Origin Fetch", curve: -26, labelDx: 6 },
      { id: "p11", from: "proxy-target-1", to: "proxy-worker-1", flow: "Origin Response", curve: 28, labelDx: -10, labelDy: 10 },
      { id: "p12", from: "proxy-target-2", to: "proxy-worker-2", flow: "Origin Response", curve: 18, labelDy: 10 },
      { id: "p13", from: "proxy-target-n", to: "proxy-worker-n", flow: "Origin Response", curve: 24, labelDx: 16, labelDy: 10 },
      { id: "p14", from: "proxy-worker-1", to: "proxy-lru", flow: "Cache Access", curve: 20, labelDx: -22 },
      { id: "p15", from: "proxy-worker-2", to: "proxy-lru", flow: "Cache Access", labelDx: -12 },
      { id: "p16", from: "proxy-worker-n", to: "proxy-lru", flow: "Cache Access", curve: -20, labelDx: 20 },
      { id: "p17", from: "proxy-worker-1", to: "proxy-logging", flow: "Request Logs", curve: -36, labelDx: 10, labelDy: -8 },
      { id: "p18", from: "proxy-worker-2", to: "proxy-logging", flow: "Request Logs", curve: -12, labelDy: -8 },
      { id: "p19", from: "proxy-worker-n", to: "proxy-logging", flow: "Request Logs", curve: 14, labelDx: 20, labelDy: -8 },
      { id: "p20", from: "proxy-lru", to: "proxy-hashmap", flow: "Key Index", labelDx: -18 },
      { id: "p21", from: "proxy-lru", to: "proxy-dll", flow: "LRU Order" },
      { id: "p22", from: "proxy-lru", to: "proxy-mutex", flow: "Lock Guard", labelDx: 14 },
      { id: "p23", from: "proxy-worker-1", to: "proxy-main-socket", flow: "Write Back", curve: 32, labelDx: 36, labelDy: -8 },
      { id: "p24", from: "proxy-worker-2", to: "proxy-main-socket", flow: "Write Back", curve: 16, labelDx: 24, labelDy: -8 },
      { id: "p25", from: "proxy-worker-n", to: "proxy-main-socket", flow: "Write Back", labelDx: 18, labelDy: -6 },
      { id: "p26", from: "proxy-main-socket", to: "proxy-client-1", flow: "HTTP Response" },
      { id: "p27", from: "proxy-main-socket", to: "proxy-client-2", flow: "HTTP Response", curve: -22, labelDx: 40, labelDy: 8 },
      { id: "p28", from: "proxy-main-socket", to: "proxy-client-n", flow: "HTTP Response", curve: -44, labelDx: 44, labelDy: 12 },
    ],
  },
  {
    id: "tradenexus",
    title: "TradeNexus",
    subtitle: "SDE-3 resilient AI trading architecture",
    overview:
      "Production-grade layered system with gateway controls, cache-first reads, dual-path analytics, async workers, and end-to-end observability.",
    canvas: { width: 1500, height: 820 },
    nodes: [
      {
        id: "tn-react",
        label: "React App",
        category: "frontend",
        x: 1100,
        y: 90,
        role: "Primary client experience for traders; consumes REST and AI analysis responses.",
        tech: ["React", "Realtime UI"],
      },
      {
        id: "tn-ui-news",
        label: "News Feed",
        category: "frontend",
        x: 900,
        y: 220,
        role: "Renders curated market and company news for tracked symbols.",
        tech: ["Frontend Module"],
      },
      {
        id: "tn-ui-stock",
        label: "Stock Analysis",
        category: "frontend",
        x: 1030,
        y: 220,
        role: "Displays charting indicators and computed technical signals.",
        tech: ["Frontend Module"],
      },
      {
        id: "tn-ui-watch",
        label: "Watchlist",
        category: "frontend",
        x: 1160,
        y: 220,
        role: "Manages user watchlists and tracked assets.",
        tech: ["Frontend Module"],
      },
      {
        id: "tn-ui-live",
        label: "Live Prices",
        category: "frontend",
        x: 1290,
        y: 220,
        role: "Streams low-latency quote updates for selected tickers.",
        tech: ["Frontend Module"],
      },
      {
        id: "tn-ui-ai",
        label: "AI Analysis",
        category: "frontend",
        x: 1420,
        y: 220,
        role: "Surface for AI-driven Buy/Sell/Hold explanations.",
        tech: ["Frontend Module"],
      },
      {
        id: "tn-auth",
        label: "Auth + Rate Limiter",
        category: "service",
        x: 300,
        y: 90,
        role: "Applies JWT auth, tenant rules and per-user throttling at ingress.",
        tech: ["JWT", "RBAC", "Rate Limits"],
      },
      {
        id: "tn-api",
        label: "Node.js API Gateway",
        category: "api",
        x: 300,
        y: 220,
        role: "Central router for frontend requests, cache checks and service orchestration.",
        tech: ["Express", "Typed APIs"],
      },
      {
        id: "tn-cache",
        label: "Redis Cache",
        category: "cache",
        x: 500,
        y: 90,
        role: "Caches hot quotes, news snapshots and recommendation payloads.",
        tech: ["Redis", "TTL"],
      },
      {
        id: "tn-rag",
        label: "Python RAG API",
        category: "service",
        x: 640,
        y: 220,
        role: "Runs retrieval-augmented analysis and AI strategy synthesis.",
        tech: ["Python", "LangChain"],
      },
      {
        id: "tn-risk",
        label: "Risk & Policy Engine",
        category: "service",
        x: 820,
        y: 220,
        role: "Applies guardrails, position limits and policy checks before recommendation release.",
        tech: ["Risk Rules", "Policy Engine"],
      },
      {
        id: "tn-market",
        label: "Stock Data API",
        category: "service",
        x: 120,
        y: 360,
        role: "Serves market quotes, OHLC candles and symbol metadata.",
        tech: ["Market Feed Adapters"],
      },
      {
        id: "tn-news",
        label: "News API",
        category: "service",
        x: 300,
        y: 360,
        role: "Fetches and normalizes market-moving news with ticker context.",
        tech: ["News Aggregation"],
      },
      {
        id: "tn-search",
        label: "Search API",
        category: "service",
        x: 480,
        y: 360,
        role: "Powers quick instrument and topic lookup with ranked matching.",
        tech: ["Indexed Search"],
      },
      {
        id: "tn-watch-svc",
        label: "Watchlist Service",
        category: "service",
        x: 640,
        y: 360,
        role: "Manages user watchlists, alerts and preference metadata.",
        tech: ["CRUD Service", "User Context"],
      },
      {
        id: "tn-retriever",
        label: "Retriever (ChromaDB)",
        category: "service",
        x: 800,
        y: 360,
        role: "Executes semantic retrieval and context stitching for AI prompts.",
        tech: ["Retriever", "Top-K Search"],
      },
      {
        id: "tn-reco",
        label: "Recommendation Engine",
        category: "service",
        x: 960,
        y: 360,
        role: "Combines AI output + risk decisions into final Buy/Sell/Hold response.",
        tech: ["Decision Scoring", "Strategy Rules"],
      },
      {
        id: "tn-sentinel",
        label: "SentinelDataCore",
        category: "external",
        x: 960,
        y: 500,
        role: "External market pipeline feeding normalized stock and news datasets.",
        tech: ["External API"],
      },
      {
        id: "tn-openai",
        label: "OpenAI API",
        category: "external",
        x: 1180,
        y: 500,
        role: "LLM provider used by RAG API for grounded recommendation reasoning.",
        tech: ["GPT API"],
      },
      {
        id: "tn-queue",
        label: "Async Job Queue",
        category: "service",
        x: 640,
        y: 500,
        role: "Runs non-blocking ingestion, re-indexing and backfill jobs.",
        tech: ["Queue Workers"],
      },
      {
        id: "tn-vector",
        label: "Vector Store (ChromaDB)",
        category: "database",
        x: 740,
        y: 650,
        role: "Stores embeddings for context retrieval in analysis requests.",
        tech: ["ChromaDB"],
      },
      {
        id: "tn-news-db",
        label: "News Database",
        category: "database",
        x: 960,
        y: 650,
        role: "Persistent storage for normalized articles and sentiment metadata.",
        tech: ["PostgreSQL / MongoDB"],
      },
      {
        id: "tn-stock-db",
        label: "Stock Database",
        category: "database",
        x: 1180,
        y: 650,
        role: "Stores historical prices, indicators and market snapshots.",
        tech: ["Time-series DB"],
      },
      {
        id: "tn-portfolio-db",
        label: "Portfolio Database",
        category: "database",
        x: 520,
        y: 650,
        role: "Stores user watchlists, positions and personalized strategy state.",
        tech: ["Relational DB"],
      },
      {
        id: "tn-observability",
        label: "Observability",
        category: "service",
        x: 1380,
        y: 560,
        role: "Centralized traces, metrics and logs for APIs, workers and model calls.",
        tech: ["OpenTelemetry", "Dashboards"],
      },
    ],
    edges: [
      { id: "t1", from: "tn-react", to: "tn-api", flow: "HTTP Requests", curve: -30, labelDx: -20, labelDy: -8 },
      { id: "t2", from: "tn-react", to: "tn-rag", flow: "AI Analysis", curve: 26, labelDx: -18, labelDy: -10 },
      { id: "t3", from: "tn-react", to: "tn-ui-news", flow: "Render", labelDy: -8 },
      { id: "t4", from: "tn-react", to: "tn-ui-stock", flow: "Render", labelDy: -8 },
      { id: "t5", from: "tn-react", to: "tn-ui-watch", flow: "Render", labelDy: -8 },
      { id: "t6", from: "tn-react", to: "tn-ui-live", flow: "Render", labelDy: -8 },
      { id: "t7", from: "tn-react", to: "tn-ui-ai", flow: "Render", labelDy: -8 },
      { id: "t8", from: "tn-api", to: "tn-auth", flow: "JWT + ACL", labelDx: -20, labelDy: -8 },
      { id: "t9", from: "tn-auth", to: "tn-api", flow: "Allow/Deny", labelDx: -38, labelDy: 10 },
      { id: "t10", from: "tn-api", to: "tn-cache", flow: "Cache Check", labelDy: -10 },
      { id: "t11", from: "tn-cache", to: "tn-api", flow: "Cache Hit", labelDy: 10 },
      { id: "t12", from: "tn-api", to: "tn-market", flow: "Stock Query", labelDx: -32 },
      { id: "t13", from: "tn-api", to: "tn-news", flow: "News Query" },
      { id: "t14", from: "tn-api", to: "tn-search", flow: "Search Query", labelDx: 24 },
      { id: "t15", from: "tn-api", to: "tn-watch-svc", flow: "Watchlist Ops", labelDx: 42 },
      { id: "t16", from: "tn-rag", to: "tn-retriever", flow: "Context Retrieve", labelDx: 18, labelDy: -8 },
      { id: "t17", from: "tn-retriever", to: "tn-vector", flow: "Vector Search", labelDx: -16, labelDy: -6 },
      { id: "t18", from: "tn-rag", to: "tn-openai", flow: "LLM Completion", curve: 28, labelDx: 50, labelDy: -12 },
      { id: "t19", from: "tn-rag", to: "tn-risk", flow: "Signal Check", labelDy: -8 },
      { id: "t20", from: "tn-risk", to: "tn-reco", flow: "Policy-Scored", labelDy: -8 },
      { id: "t21", from: "tn-reco", to: "tn-api", flow: "Final Decision", curve: -26, labelDx: -22, labelDy: 10 },
      { id: "t22", from: "tn-market", to: "tn-sentinel", flow: "Feed Pull", curve: -24, labelDy: -10 },
      { id: "t23", from: "tn-news", to: "tn-sentinel", flow: "News Pull", curve: -12, labelDy: -10 },
      { id: "t24", from: "tn-search", to: "tn-sentinel", flow: "Unified Search", curve: 10, labelDy: -10 },
      { id: "t25", from: "tn-sentinel", to: "tn-news-db", flow: "News Persist", labelDx: -12 },
      { id: "t26", from: "tn-sentinel", to: "tn-stock-db", flow: "Stock Persist", labelDx: 14 },
      { id: "t27", from: "tn-watch-svc", to: "tn-portfolio-db", flow: "Portfolio Persist", labelDx: -12 },
      { id: "t28", from: "tn-api", to: "tn-queue", flow: "Async Tasks", curve: 30, labelDx: 12, labelDy: 6 },
      { id: "t29", from: "tn-queue", to: "tn-vector", flow: "Re-index Jobs", labelDx: -20 },
      { id: "t30", from: "tn-api", to: "tn-react", flow: "Response Payload", curve: 32, labelDx: 12, labelDy: 10 },
      { id: "t31", from: "tn-api", to: "tn-observability", flow: "API Metrics", curve: 40, labelDx: 56, labelDy: -8 },
      { id: "t32", from: "tn-rag", to: "tn-observability", flow: "Model Traces", curve: 30, labelDx: 56 },
      { id: "t33", from: "tn-queue", to: "tn-observability", flow: "Worker Logs", curve: 24, labelDx: 62, labelDy: 10 },
      { id: "t34", from: "tn-sentinel", to: "tn-observability", flow: "Pipeline Metrics", curve: -22, labelDx: 58, labelDy: -4 },
    ],
  },
];
