import { ArchitectureProject } from "@/types";

export const architectureProjects: ArchitectureProject[] = [
  {
    id: "sentinel-datacore",
    title: "SentinelDataCore",
    subtitle: "Real-time stock API with JWT + LRU caching",
    overview:
      "Request flow starts from dashboard clients, moves through Express API gateway, then fans into auth, market-data, cache and persistence layers.",
    canvas: { width: 1200, height: 720 },
    nodes: [
      {
        id: "sentinel-ui",
        label: "Trader Dashboard",
        category: "frontend",
        x: 140,
        y: 220,
        role: "Consumes market endpoints and receives real-time updates over WebSockets.",
        tech: ["React", "Axios", "WebSockets"],
      },
      {
        id: "sentinel-api",
        label: "API Gateway",
        category: "api",
        x: 420,
        y: 220,
        role: "Central entry point for REST routes, validation, auth checks and response shaping.",
        tech: ["Node.js", "Express", "JWT Middleware"],
      },
      {
        id: "sentinel-auth",
        label: "Auth Service",
        category: "service",
        x: 420,
        y: 90,
        role: "Issues and verifies JWT tokens for protected API requests.",
        tech: ["JWT", "bcrypt", "Token Policies"],
      },
      {
        id: "sentinel-market",
        label: "Market Data Service",
        category: "service",
        x: 700,
        y: 220,
        role: "Generates and normalizes stock ticks before serving API and push channels.",
        tech: ["Node.js", "Schedulers", "Stream Processing"],
      },
      {
        id: "sentinel-cache",
        label: "LRU Cache Layer",
        category: "cache",
        x: 700,
        y: 100,
        role: "Stores hot query results to reduce repeated database reads and lower latency.",
        tech: ["LRU", "In-memory Indexing"],
      },
      {
        id: "sentinel-db",
        label: "MongoDB",
        category: "database",
        x: 980,
        y: 250,
        role: "Persists market snapshots, user-specific metadata and API data records.",
        tech: ["MongoDB", "Indexes", "Aggregations"],
      },
      {
        id: "sentinel-ws",
        label: "WebSocket Broadcaster",
        category: "service",
        x: 700,
        y: 360,
        role: "Pushes incremental market updates to subscribed connected clients.",
        tech: ["WebSockets", "Pub/Sub"],
      },
      {
        id: "sentinel-feed",
        label: "Mock Market Feed",
        category: "external",
        x: 980,
        y: 110,
        role: "External/mock feed source used for ingestion and stream simulation.",
        tech: ["External Data Source"],
      },
    ],
    edges: [
      { id: "s1", from: "sentinel-ui", to: "sentinel-api", flow: "REST Request" },
      { id: "s2", from: "sentinel-api", to: "sentinel-auth", flow: "Token Verify" },
      { id: "s3", from: "sentinel-api", to: "sentinel-cache", flow: "Cache Lookup" },
      { id: "s4", from: "sentinel-cache", to: "sentinel-api", flow: "Cache Hit" },
      { id: "s5", from: "sentinel-api", to: "sentinel-market", flow: "Query Dispatch" },
      { id: "s6", from: "sentinel-market", to: "sentinel-db", flow: "Read/Write" },
      { id: "s7", from: "sentinel-market", to: "sentinel-ws", flow: "Tick Events" },
      { id: "s8", from: "sentinel-ws", to: "sentinel-ui", flow: "Realtime Push" },
      { id: "s9", from: "sentinel-feed", to: "sentinel-market", flow: "Data Ingest" },
    ],
  },
  {
    id: "ums-chatbot",
    title: "UMS Chatbot",
    subtitle: "RAG pipeline for university query resolution",
    overview:
      "User prompts are orchestrated through retrieval and generation services, blending FAISS semantic search with LLM-powered final responses.",
    canvas: { width: 1200, height: 720 },
    nodes: [
      {
        id: "ums-ui",
        label: "Chat UI",
        category: "frontend",
        x: 130,
        y: 250,
        role: "Collects user questions and streams bot responses in a conversational interface.",
        tech: ["React", "State Management"],
      },
      {
        id: "ums-api",
        label: "Node API",
        category: "api",
        x: 380,
        y: 250,
        role: "Receives prompts, manages session context, and forwards to orchestration layer.",
        tech: ["Node.js", "Express"],
      },
      {
        id: "ums-orch",
        label: "RAG Orchestrator",
        category: "service",
        x: 620,
        y: 250,
        role: "Coordinates embedding retrieval, prompt assembly and model invocation pipeline.",
        tech: ["LangChain", "Python"],
      },
      {
        id: "ums-faiss",
        label: "FAISS Vector Index",
        category: "database",
        x: 860,
        y: 160,
        role: "Stores vector embeddings for fast semantic nearest-neighbor retrieval.",
        tech: ["FAISS", "Embeddings"],
      },
      {
        id: "ums-llm",
        label: "LLM Gateway",
        category: "external",
        x: 860,
        y: 330,
        role: "Generates grounded answers from retrieved context plus user prompt.",
        tech: ["OpenAI API", "Prompt Engineering"],
      },
      {
        id: "ums-ingest",
        label: "Document Ingestion",
        category: "service",
        x: 620,
        y: 100,
        role: "Ingests university documents, chunks text and updates embeddings.",
        tech: ["Python", "Chunking", "ETL"],
      },
      {
        id: "ums-corpus",
        label: "Academic Corpus",
        category: "database",
        x: 1020,
        y: 100,
        role: "Source documents for admissions, departments, policies and curriculum.",
        tech: ["PDF", "Structured Docs"],
      },
    ],
    edges: [
      { id: "u1", from: "ums-ui", to: "ums-api", flow: "User Query" },
      { id: "u2", from: "ums-api", to: "ums-orch", flow: "Prompt Task" },
      { id: "u3", from: "ums-orch", to: "ums-faiss", flow: "Semantic Search" },
      { id: "u4", from: "ums-faiss", to: "ums-orch", flow: "Top-K Context" },
      { id: "u5", from: "ums-orch", to: "ums-llm", flow: "Grounded Prompt" },
      { id: "u6", from: "ums-llm", to: "ums-api", flow: "Generated Answer" },
      { id: "u7", from: "ums-api", to: "ums-ui", flow: "Response Stream" },
      { id: "u8", from: "ums-corpus", to: "ums-ingest", flow: "Docs Input" },
      { id: "u9", from: "ums-ingest", to: "ums-faiss", flow: "Embedding Upsert" },
    ],
  },
  {
    id: "proxy-server",
    title: "Multi-Threaded Proxy Server",
    subtitle: "High-throughput HTTP proxy with O(1) LRU cache",
    overview:
      "Incoming client requests are accepted by a listener, dispatched to worker threads, resolved via cache-first routing and forwarded to origin servers when needed.",
    canvas: { width: 1200, height: 720 },
    nodes: [
      {
        id: "proxy-clients",
        label: "HTTP Clients",
        category: "frontend",
        x: 140,
        y: 250,
        role: "Browser/consumer clients issuing proxied HTTP requests.",
        tech: ["HTTP/1.1", "Socket Clients"],
      },
      {
        id: "proxy-listener",
        label: "Listener Socket",
        category: "infra",
        x: 380,
        y: 250,
        role: "Accepts inbound socket connections and queues them for worker handling.",
        tech: ["POSIX / WinAPI Sockets"],
      },
      {
        id: "proxy-workers",
        label: "Worker Thread Pool",
        category: "service",
        x: 620,
        y: 250,
        role: "Processes connections concurrently with mutex and condition-variable synchronization.",
        tech: ["C++ Threads", "Mutex", "Condition Variable"],
      },
      {
        id: "proxy-cache",
        label: "LRU Cache",
        category: "cache",
        x: 620,
        y: 120,
        role: "Caches hot responses via hashmap + doubly linked list for O(1) lookup/eviction.",
        tech: ["unordered_map", "Doubly Linked List"],
      },
      {
        id: "proxy-router",
        label: "Request Router",
        category: "service",
        x: 860,
        y: 250,
        role: "Parses target URL and routes fetch operations to correct origin endpoints.",
        tech: ["HTTP Parser", "Routing Logic"],
      },
      {
        id: "proxy-origin",
        label: "Origin Servers",
        category: "external",
        x: 1040,
        y: 250,
        role: "Upstream servers providing cache-miss content to the proxy.",
        tech: ["External HTTP Servers"],
      },
      {
        id: "proxy-metrics",
        label: "Metrics & Logging",
        category: "database",
        x: 860,
        y: 390,
        role: "Tracks cache hit/miss, throughput and request diagnostics in real time.",
        tech: ["Structured Logs", "Runtime Metrics"],
      },
    ],
    edges: [
      { id: "p1", from: "proxy-clients", to: "proxy-listener", flow: "TCP Connection" },
      { id: "p2", from: "proxy-listener", to: "proxy-workers", flow: "Socket Dispatch" },
      { id: "p3", from: "proxy-workers", to: "proxy-cache", flow: "Cache Probe" },
      { id: "p4", from: "proxy-cache", to: "proxy-workers", flow: "Cached Payload" },
      { id: "p5", from: "proxy-workers", to: "proxy-router", flow: "Cache Miss Route" },
      { id: "p6", from: "proxy-router", to: "proxy-origin", flow: "Origin Fetch" },
      { id: "p7", from: "proxy-origin", to: "proxy-workers", flow: "Origin Response" },
      { id: "p8", from: "proxy-workers", to: "proxy-metrics", flow: "Hit/Miss + Latency" },
      { id: "p9", from: "proxy-workers", to: "proxy-clients", flow: "HTTP Response" },
    ],
  },
  {
    id: "tradenexus",
    title: "TradeNexus",
    subtitle: "AI trading recommendation platform",
    overview:
      "Live market data feeds a feature and inference pipeline, then recommendations are served to clients with retrieval context from ChromaDB memory.",
    canvas: { width: 1200, height: 720 },
    nodes: [
      {
        id: "tn-ui",
        label: "Trader UI",
        category: "frontend",
        x: 130,
        y: 240,
        role: "Displays market snapshots and Buy/Sell/Hold recommendations to end users.",
        tech: ["React", "Charts", "Realtime UI"],
      },
      {
        id: "tn-api",
        label: "API Orchestrator",
        category: "api",
        x: 380,
        y: 240,
        role: "Coordinates strategy requests, invokes inference chain and assembles final output.",
        tech: ["Node.js", "Express"],
      },
      {
        id: "tn-ingest",
        label: "Market Ingestion Service",
        category: "service",
        x: 620,
        y: 130,
        role: "Pulls/streams real-time financial data and normalizes it for downstream services.",
        tech: ["Python", "Data Pipelines"],
      },
      {
        id: "tn-feature",
        label: "Feature Engine",
        category: "service",
        x: 620,
        y: 260,
        role: "Computes indicators and signal features used by the recommendation model.",
        tech: ["Pandas", "Signal Processing"],
      },
      {
        id: "tn-gpt",
        label: "GPT Decision Engine",
        category: "external",
        x: 860,
        y: 260,
        role: "Generates contextual Buy/Sell/Hold recommendation from engineered features.",
        tech: ["OpenAI API", "Prompt Templates"],
      },
      {
        id: "tn-chroma",
        label: "ChromaDB Context Store",
        category: "database",
        x: 860,
        y: 120,
        role: "Stores historical context embeddings to improve consistency and explanation quality.",
        tech: ["ChromaDB", "Vector Retrieval"],
      },
      {
        id: "tn-rec",
        label: "Recommendation Service",
        category: "service",
        x: 1040,
        y: 260,
        role: "Fuses model output + risk rules and returns final recommendation payload.",
        tech: ["Scoring Rules", "Risk Filters"],
      },
      {
        id: "tn-store",
        label: "Trade History Store",
        category: "database",
        x: 620,
        y: 390,
        role: "Persists generated recommendations and user decision history for analytics.",
        tech: ["PostgreSQL / MongoDB"],
      },
    ],
    edges: [
      { id: "t1", from: "tn-ui", to: "tn-api", flow: "Recommendation Request" },
      { id: "t2", from: "tn-api", to: "tn-feature", flow: "Compute Signals" },
      { id: "t3", from: "tn-ingest", to: "tn-feature", flow: "Live Market Data" },
      { id: "t4", from: "tn-feature", to: "tn-gpt", flow: "Feature Prompt" },
      { id: "t5", from: "tn-chroma", to: "tn-gpt", flow: "Context Retrieval" },
      { id: "t6", from: "tn-gpt", to: "tn-rec", flow: "Raw Recommendation" },
      { id: "t7", from: "tn-rec", to: "tn-api", flow: "Final Decision" },
      { id: "t8", from: "tn-api", to: "tn-store", flow: "Audit Persist" },
      { id: "t9", from: "tn-api", to: "tn-ui", flow: "Buy/Sell/Hold Payload" },
    ],
  },
];
